// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3eUxeeyPlQiuiCUcJGm8T5XeymIS3K0s',
    appId: '1:123338822202:web:b8f321854c29b56b2c1b03',
    messagingSenderId: '123338822202',
    projectId: 'study-case-flutter',
    authDomain: 'study-case-flutter.firebaseapp.com',
    storageBucket: 'study-case-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqwLzgUsW3sojh6FPpdUWavh71ZZit5pw',
    appId: '1:123338822202:android:be0875bc035dad532c1b03',
    messagingSenderId: '123338822202',
    projectId: 'study-case-flutter',
    storageBucket: 'study-case-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBACGRY7XsMRRFUPL8CuXYlFfU5HkDnBHc',
    appId: '1:123338822202:ios:fdd76c4cfd3c511a2c1b03',
    messagingSenderId: '123338822202',
    projectId: 'study-case-flutter',
    storageBucket: 'study-case-flutter.firebasestorage.app',
    iosBundleId: 'com.example.studyCase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBACGRY7XsMRRFUPL8CuXYlFfU5HkDnBHc',
    appId: '1:123338822202:ios:fdd76c4cfd3c511a2c1b03',
    messagingSenderId: '123338822202',
    projectId: 'study-case-flutter',
    storageBucket: 'study-case-flutter.firebasestorage.app',
    iosBundleId: 'com.example.studyCase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3eUxeeyPlQiuiCUcJGm8T5XeymIS3K0s',
    appId: '1:123338822202:web:a9dd507a8791b2202c1b03',
    messagingSenderId: '123338822202',
    projectId: 'study-case-flutter',
    authDomain: 'study-case-flutter.firebaseapp.com',
    storageBucket: 'study-case-flutter.firebasestorage.app',
  );
}
